### ISSUE TITLE
OSError: /b/home/uha/hfawaz-datas/dl-tsc//archives/TSC/Coffee/Coffee_TRAIN not found.

### ISSUE THREAD

**Issue by allaabdella2** [hfawaz/dl-4-tsc#33]
Method:  TSC Coffee fcn _itr_8
Traceback (most recent call last):
  File "main.py", line 150, in <module>
    datasets_dict = read_dataset(root_dir, archive_name, dataset_name)
  File "/content/dl-4-tsc/utils/utils.py", line 105, in read_dataset
    x_train, y_train = readucr(file_name + '_TRAIN')
  File "/content/dl-4-tsc/utils/utils.py", line 33, in readucr
    data = np.loadtxt(filename, delimiter=',')
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: /b/home/uha/hfawaz-datas/dl-tsc//archives/TSC/Coffee/Coffee_TRAIN not found.

**Comment by JinYang88** [comment]
Got the same error.

**Comment by sabooakhter** [comment]
You just have to change the root_dir name in the main.py script, honestly I do believe the author shouldve made that dynamic with a load from the os package, but whatever.

**Comment by neensimpson** [comment]
I changed it to match my setup but it's still giving that error. I think the path is fine because it created the results folder no problem. The issue seems to be that the data isn't in the format it expects it to be. The UTS data does split into test and train but its txt not tsv as expected I converted one of them to try it, removed an errant '/' in the path and it got further than before. I haven't been able to get this to work properly yet. 

Also the Multivariate time series database is now missing from the linked site
